import { createPinia } from 'pinia'

const pinia = createPinia()

export default pinia

// 导出所有 store
export { useUserStore } from './modules/user'
export { useAppStore } from './modules/app'
export { useFarmTaskStore } from './modules/farmTask'
export { useLaborStore } from './modules/labor'
export { useIndicatorStore } from './modules/indicators'
export { useSummaryStore } from './modules/summary'
export { useSeedSourceStore } from './modules/seedSource'
export { useSeedlingStore } from './modules/seedling'
export { useOrderDataStore } from './modules/orderData'
export { useProductionPlanStore } from './modules/productionPlan'
export { useTechSolutionStore } from './modules/techSolution'
export { usePurchasePlanStore } from './modules/purchasePlan'
export { useGreenhouseStore } from './modules/greenhouse'
export { useHarvestStore } from './modules/harvest'
export { useFertilizerStore } from './modules/fertilizer'
export { usePlantingStore } from './modules/planting'
export { usePlantSettingStore } from './modules/plantSetting'
export { useDeviceSystemStore } from './modules/deviceSystem'
export { useAreaSystemStore } from './modules/areaSystem'
export { useFarmPartitionStore } from './modules/farmPartition'
export { useAlarmConfigStore } from './modules/alarmConfig'
export { useDeviceDistributionStore } from './modules/deviceDistribution'
export { useWaterFertilizerStore } from './modules/waterFertilizer'
export { useEnergyConfigStore, ENERGY_TYPES } from './modules/energyConfig'
export { useZoneStore } from './modules/zone'
export { useCostStore } from './modules/cost'
export { useProcessDefinitionStore } from './modules/processDefinition'
export { useDeviceStore } from './modules/device'
export { useDepartmentStore } from './modules/department'
export { useSystemConfigStore, CATEGORY_TABS } from './modules/systemConfig'
export { useBaseStore } from './modules/baseStore'
export { useBlockStore } from './modules/blockStore'
export { usePlantingRecordStore } from './modules/plantingRecordStore'
export { useCameraStore } from './modules/camera'
export { useApprovalLevelStore } from './modules/approvalLevel'
export { useNotificationSettingsStore } from './modules/notificationSettings'
export { useCropVarietyStore } from './modules/cropVariety'
export { useAuthorityStore } from './modules/authority'
export { useApprovalWorkflowStore } from './modules/approvalWorkflow'
export { useApprovalStore } from './modules/approval'
export { usePlantLabelStore } from './modules/plantLabel'
// 库存模块
export { useInboundStore } from './modules/inventory'
export { useMaterialReturnStore } from './modules/inventory'
export { useMaterialRequestStore } from './modules/inventory'
export { useExecuteStore } from './modules/inventory'
export { useWarehouseMaterialStore } from './modules/inventory'
export { useWarehouseStore } from './modules/inventory'
export { useMaterialTypeStore } from './modules/inventory'
export { useSupplierStore } from './modules/inventory'
